- type: entity
  id: SquadBase
  abstract: true
  categories:
  - "hideSpawnMenu"
  components:
  - type: SquadTeam
    background:
      sprite: _CM14/Interface/cm_job_icons.rsi
      state: hudsquad

- type: entity
  parent: SquadBase
  id: SquadAlpha
  name: Alpha
  components:
  - type: SquadTeam
    color: "#E61919"
    accessLevel: CMAccessAlpha

- type: entity
  parent: SquadBase
  id: SquadBravo
  name: Bravo
  components:
  - type: SquadTeam
    color: "#FFC32D"
    accessLevel: CMAccessBravo

- type: entity
  parent: SquadBase
  id: SquadCharlie
  name: Charlie
  components:
  - type: SquadTeam
    color: "#C864C8"
    accessLevel: CMAccessCharlie

- type: entity
  parent: SquadBase
  id: SquadDelta
  name: Delta
  components:
  - type: SquadTeam
    color: "#4148C8"
    accessLevel: CMAccessDelta
