- type: job
  parent: CMJobBase
  id: CMChiefEngineer
  name: cm-job-name-chief-engineer
  description: cm-job-description-chief-engineer
  playTimeTracker: CMJobChiefEngineer
  requirements:
    - !type:DepartmentTimeRequirement
      department: CMEngineering
      time: 36000 # 10 hours
    - !type:DepartmentTimeRequirement
      department: CMMilitaryPolice
      time: 3600 # 1 hour
  weight: 5
  startingGear: CMGearChiefEngineer
  icon: "CMJobIconChiefEngineer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-aso
  canBeAntag: false
  accessGroups:
  - CMCE
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 3
      engineer: 3
      fireman: 1
      intel: 1
      jtac: 4
      leadership: 3
      navigations: 1
      overwatch: 1
      police: 1
      powerLoader: 2
    - type: MarineOrders

- type: startingGear
  id: CMGearChiefEngineer
  equipment:
    jumpsuit: CMJumpsuitChiefEngineer
    back: CMSatchelEngineer
    shoes: CMBootsBrown
    gloves: CMHandsInsulated
    id: CMIDCardChiefEngineer
    ears: CMHeadsetCE
    belt: CMBeltUtilityFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointChiefEngineer
  name: chief engineer spawn point
  components:
  - type: SpawnPoint
    job_id: CMChiefEngineer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: chief_engineer
      
- type: playTimeTracker
  id: CMJobChiefEngineer
