- type: job
  parent: CMJobBase
  id: CMMaintTech
  name: cm-job-name-maint-tech
  description: cm-job-description-maint-tech
  playTimeTracker: CMJobMaintTech
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMMarine
    time: 3600 # 1 hours
  startingGear: CMGearMaintTech
  icon: "CMJobIconMaintTech"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-ce
  canBeAntag: true
  accessGroups:
  - MaintTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      domestics: 1
      construction: 3
      engineer: 3
      powerLoader: 2

- type: startingGear
  id: CMGearMaintTech
  equipment:
    jumpsuit: CMJumpsuitMaintTech
    back: CMSatchelEngineer
    shoes: CMBootsBrown
    gloves: CMHandsInsulated
    id: CMIDCardMaintTech
    ears: CMHeadsetEngineer
    belt: CMBeltUtilityFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointMaintTech
  name: maint tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMMaintTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: maintenance_tech

- type: playTimeTracker
  id: CMJobMaintTech
