- type: job
  id: MaintTech
  parent: JobBaseCM
  name: job-name-maint-tech
  description: job-description-maint-tech
  playTimeTracker: JobMaintTech
  requirements:
  - !type:DepartmentTimeRequirement
    department: Marine
    time: 3600 # 1 hours
  startingGear: MaintTechGear
  icon: "JobIconMaintTech"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-ce
  canBeAntag: true
  accessGroups:
  - MaintTech

- type: startingGear
  id: MaintTechGear
  equipment:
    jumpsuit: CMJumpsuitMaintTech
    back: CMBackpackEngineer
    shoes: CMBootsBrown
    gloves: CMHandsInsulated
    id: MaintTechIDCard
    ears: CMHeadsetEngineer
    belt: CMBeltUtilityFilled
  satchel: CMSatchelEngineer

- type: entity
  id: SpawnPointMaintTech
  parent: CMSpawnPointJobBase
  name: maint tech spawn point
  components:
  - type: SpawnPoint
    job_id: MaintTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: maintenance_tech
