- type: job
  id: CMOrdnanceTech
  parent: CMJobBase
  name: cm-job-name-ordnance-tech
  description: cm-job-description-ordnance-Tech
  playTimeTracker: CMJobOrdnanceTech
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMEngineering
    time: 3600 # 1 hours
  startingGear: CMGearOrdnanceTech
  icon: "CMJobIconOrdnanceTech"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-ce
  canBeAntag: true
  accessGroups:
  - OT
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 3
      engineer: 3
      powerLoader: 2

- type: startingGear
  id: CMGearOrdnanceTech
  equipment:
    jumpsuit: CMJumpsuitOrdnanceTech
    back: CMSatchelEngineer
    shoes: CMBootsBrown
    gloves: CMHandsInsulated
    id: CMIDCardOrdnanceTech
    ears: CMHeadsetEngineer
    belt: CMBeltUtilityFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointOrdnanceTech
  name: ordnance tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMOrdnanceTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: ordnance_tech

- type: playTimeTracker
  id: CMJobOrdnanceTech
