- type: job
  id: MarineCMO
  parent: JobBaseCM
  name: job-name-cm-cmo
  description: job-description-cm-cmo
  playTimeTracker: JobMarineCMO
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 36000 # 10 hours
  weight: 5
  startingGear: MarineCMOGear
  icon: "JobIconMarineCMO"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-cm14-co
  canBeAntag: false
  accessGroups:
  - CMCMO
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      fireman: 1
      intel: 1
      jtac: 3
      leadership: 2
      medical: 3
      overwatch: 1
      police: 1
      research: 1
      surgery: 2

- type: startingGear
  id: MarineCMOGear
  equipment:
    jumpsuit: CMJumpsuitCMO
    outerClothing: CMCoatLong
    back: CMBackpackMedical
    gloves: CMHandsLatex
    shoes: ClothingShoesColorWhite
    head: CMHeadCapCMO
    id: MarineCMOIDCard
    ears: CMHeadsetCMO
    belt: CMBeltMedicalFilled
  satchel: CMSatchelMedical

- type: entity
  id: CMSpawnPointCMO
  parent: CMSpawnPointJobBase
  name: chief medical officer spawn point
  components:
  - type: SpawnPoint
    job_id: MarineCMO
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: chief_medical_officer
