- type: job
  parent: CMJobBase
  id: CMCMO
  name: cm-job-name-cmo
  description: cm-job-description-cmo
  playTimeTracker: CMJobCMO
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMMedical
    time: 36000 # 10 hours
  weight: 5
  startingGear: CMGearCMO
  icon: "CMJobIconCMO"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-co
  canBeAntag: false
  accessGroups:
  - CMCMO
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      fireman: 1
      intel: 1
      jtac: 3
      leadership: 2
      medical: 3
      overwatch: 1
      police: 1
      research: 1
      surgery: 2
    - type: MarineOrders

- type: startingGear
  id: CMGearCMO
  equipment:
    jumpsuit: CMJumpsuitCMO
    outerClothing: CMCoatLong
    back: CMSatchelMedical
    gloves: CMHandsLatex
    shoes: ClothingShoesColorWhite
    head: CMHeadCapCMO
    id: CMIDCardCMO
    ears: CMHeadsetCMO
    belt: CMBeltMedicalFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCMO
  name: chief medical officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMCMO
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: chief_medical_officer

- type: playTimeTracker
  id: CMJobCMO
