- type: job
  parent: CMJobBase
  id: CMDoctor
  name: cm-job-name-doctor
  description: cm-job-description-doctor
  playTimeTracker: CMJobDoctor
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMMedical
    time: 3600 # 1 hours
  startingGear: CMGearDoctor
  icon: "CMJobIconDoctor"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-cmo
  canBeAntag: true
  accessGroups:
  - CMMedical
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      medical: 3
      surgery: 2

- type: startingGear
  id: CMGearDoctor
  equipment:
    jumpsuit: CMScrubsBlue
    outerClothing: CMCoatLong
    back: CMSatchelMedical
    gloves: CMHandsLatex
    shoes: ClothingShoesColorWhite
    head: CMHeadCapSurgBlue
    id: CMIDCardDoctor
    ears: CMHeadsetMedical
    belt: CMBeltMedicalFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointDoctor
  name: doctor spawn point
  components:
  - type: SpawnPoint
    job_id: CMDoctor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: doctor

- type: playTimeTracker
  id: CMJobDoctor
