- type: job
  id: Nurse
  parent: JobBaseCM
  name: job-name-nurse
  description: job-description-nurse
  playTimeTracker: JobNurse
  startingGear: NurseGear
  icon: "JobIconNurse"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-cmo
  canBeAntag: true
  accessGroups:
  - CMMedical

- type: startingGear
  id: NurseGear
  equipment:
    jumpsuit: CMScrubsNurse
    back: CMBackpackMedical
    gloves: CMHandsLatex
    shoes: ClothingShoesColorWhite
    head: CMHeadCapSurgOrange
    id: NurseIDCard
    ears: CMHeadsetMedical
    belt: CMBeltMedicalFilled
  satchel: CMSatchelMedical

- type: entity
  id: CMSpawnPointNurse
  parent: CMSpawnPointJobBase
  name: nurse spawn point
  components:
  - type: SpawnPoint
    job_id: Nurse
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: nurse
