- type: job
  parent: CMJobBase
  id: CMResearcher
  name: cm-job-name-researcher
  description: cm-job-description-researcher
  playTimeTracker: CMJobResearcher
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMMedical
    time: 18000 # 5 hours
  startingGear: CMGearResearcher
  icon: "CMJobIconResearcher"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-cmo
  canBeAntag: true
  accessGroups:
  - Researcher
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      intel: 1
      medical: 3
      research: 1
      surgery: 2

- type: startingGear
  id: CMGearResearcher
  equipment:
    jumpsuit: CMJumpsuitResearch
    back: CMSatchelMedical
    gloves: CMHandsLatex
    shoes: CMShoesDress
    id: CMIDCardResearcher
    ears: CMHeadsetResearcher

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointResearcher
  name: researcher spawn point
  components:
  - type: SpawnPoint
    job_id: CMResearcher
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: researcher

- type: playTimeTracker
  id: CMJobResearcher
