- type: job
  id: Researcher
  parent: JobBaseCM
  name: job-name-researcher
  description: job-description-researcher
  playTimeTracker: JobResearcher
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 18000 # 5 hours
  startingGear: ResearcherGear
  icon: "JobIconResearcher"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-cmo
  canBeAntag: true
  accessGroups:
  - Researcher

- type: startingGear
  id: ResearcherGear
  equipment:
    jumpsuit: CMJumpsuitResearch
    back: CMBackpackMedical
    gloves: CMHandsLatex
    shoes: CMShoesDress
    id: ResearcherIDCard
    ears: CMHeadsetResearcher
  satchel: CMSatchelMedical

- type: entity
  id: CMSpawnPointResearcher
  parent: CMSpawnPointJobBase
  name: researcher spawn point
  components:
  - type: SpawnPoint
    job_id: Researcher
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: researcher
