- type: job
  id: MilitaryPolice
  parent: JobBaseCM
  name: job-name-militarypolice
  description: job-description-militarypolice
  playTimeTracker: JobMilitaryPolice
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 36000 # 10 hours
  weight: 5
  startingGear: MilitaryPoliceGear
  icon: "JobIconMilitaryPolice"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-cmp
  canBeAntag: false
  accessGroups:
  - MP

- type: startingGear
  id: MilitaryPoliceGear
  equipment:
    jumpsuit: CMJumpsuitMPBlack
    back: CMBackpackSecurity
    shoes: CMBootsBlackFilled
    head: CMHeadBeretRed
    eyes: ClothingEyesGlassesSecurity
    gloves: CMHandsBlack
    id: MilitaryPoliceIDCard
    outerClothing: CMArmorM2MP
    ears: CMHeadsetMPO
    belt: CMBeltSecurityFilled
  satchel: CMSatchelSecurity

- type: entity
  id: SpawnPointMilitaryPolice
  parent: CMSpawnPointJobBase
  name: military police spawn point
  components:
  - type: SpawnPoint
    job_id: MilitaryPolice
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: military_police
