- type: job
  id: MilitaryWarden
  parent: JobBaseCM
  name: job-name-militarywarden
  description: job-description-militarywarden
  playTimeTracker: JobMilitaryWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 18000 # 5 hours
  weight: 5
  startingGear: MilitaryWardenGear
  icon: "JobIconMilitaryWarden"
  requireAdminNotify: false
  joinNotifyCrew: true
  supervisors: job-supervisors-chiefmp
  canBeAntag: false
  accessGroups:
  - CMWarden

- type: startingGear
  id: MilitaryWardenGear
  equipment:
    jumpsuit: CMJumpsuitWarden
    back: CMBackpackSecurity
    shoes: CMBootsBlackFilled
    head: CMHeadCapWarden
    eyes: ClothingEyesGlassesSecurity
    gloves: CMHandsBlack
    id: MilitaryWardenIDCard
    outerClothing: CMArmorM3Warden
    ears: CMHeadsetCMP
    belt: CMBeltSecurityFilled
  satchel: CMSatchelSecurity

- type: entity
  id: SpawnPointMilitaryWarden
  parent: CMSpawnPointJobBase
  name: military warden spawn point
  components:
  - type: SpawnPoint
    job_id: MilitaryWarden
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: warden
