- type: job
  id: MilitaryWarden
  parent: JobBaseCM
  name: job-name-militarywarden
  description: job-description-militarywarden
  playTimeTracker: JobMilitaryWarden
  requirements:
    - !type:DepartmentTimeRequirement
      department: MilitaryPolice
      time: 18000 # 5 hours
  weight: 5
  startingGear: MilitaryWardenGear
  icon: "JobIconMilitaryWarden"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-cmp
  canBeAntag: false
  accessGroups:
  - CMWarden
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 2
      cqc: 2
      endurance: 2
      engineer: 2
      fireman: 1
      leadership: 1
      medical: 1
      overwatch: 1
      police: 2

- type: startingGear
  id: MilitaryWardenGear
  equipment:
    jumpsuit: CMJumpsuitWarden
    back: CMBackpackSecurity
    shoes: CMBootsBlackFilled
    head: CMHeadCapWarden
    eyes: ClothingEyesGlassesSecurity
    gloves: CMHandsBlack
    id: MilitaryWardenIDCard
    outerClothing: CMArmorM3Warden
    ears: CMHeadsetCMP
    belt: CMBeltSecurityFilled
  satchel: CMSatchelSecurity

- type: entity
  id: SpawnPointMilitaryWarden
  parent: CMSpawnPointJobBase
  name: military warden spawn point
  components:
  - type: SpawnPoint
    job_id: MilitaryWarden
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: warden
