- type: job
  parent: CMJobBase
  id: CMMilitaryPolice
  name: cm-job-name-militarypolice
  description: cm-job-description-militarypolice
  playTimeTracker: CMJobMilitaryPolice
  requirements:
    - !type:DepartmentTimeRequirement
      department: CMMarine
      time: 36000 # 10 hours
  weight: 5
  startingGear: CMGearMilitaryPolice
  icon: "CMJobIconMilitaryPolice"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-cmp
  canBeAntag: false
  accessGroups:
  - MP
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 2
      endurance: 2
      fireman: 2
      police: 2

- type: startingGear
  id: CMGearMilitaryPolice
  equipment:
    jumpsuit: CMJumpsuitMPBlack
    back: CMSatchelSecurity
    shoes: CMBootsBlackFilled
    head: CMHeadBeretRed
    eyes: ClothingEyesGlassesSecurity # todo cm14 replace with cm ones
    gloves: CMHandsBlack
    id: CMIDCardMilitaryPolice
    outerClothing: CMArmorM2MP
    ears: CMHeadsetMPO
    belt: CMBeltSecurityFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointMilitaryPolice
  name: military police spawn point
  components:
  - type: SpawnPoint
    job_id: CMMilitaryPolice
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: military_police

- type: playTimeTracker
  id: CMJobMilitaryPolice
