- type: job
  id: CMCargoTech
  parent: JobBaseCM
  name: job-name-cm-cargotech
  description: job-description-cm-cargotech
  playTimeTracker: JobCMCargoTech
  startingGear: CMCargoTechGear
  icon: "JobIconCMCargoTech"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-qm
  canBeAntag: true
  accessGroups:
  - CMCargoTech

- type: startingGear
  id: CMCargoTechGear
  equipment:
    jumpsuit: CMJumpsuitCargoTech
    back: CMBackpackEngineer
    shoes: CMBootsBrown
    head: CMHeadCapCargo
    gloves: CMHandsBrown
    id: CMCargoTechIDCard
    ears: CMHeadsetRequisition
  satchel: CMSatchelEngineer

- type: entity
  id: CMSpawnPointCargoTech
  parent: CMSpawnPointJobBase
  name: cargo tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMCargoTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: cargo_tech
