- type: job
  id: MessTech
  parent: JobBaseCM
  name: job-name-messtech
  description: job-description-messtech
  playTimeTracker: JobMessTech
  startingGear: MessTechGear
  icon: "JobIconMessTech"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-aso
  canBeAntag: true
  accessGroups:
  - MessTech

- type: startingGear
  id: MessTechGear
  equipment:
    head: ClothingHeadHatChef
    jumpsuit: CMJumpsuitMessTech
    outerClothing: CMCoatMessTech
    back: CMBackpack
    shoes: CMBootsBrown
    id: MessTechIDCard
    ears: CMHeadsetChef
  satchel: CMSatchel

- type: entity
  id: SpawnPointMessTech
  parent: CMSpawnPointJobBase
  name: mess tech spawn point
  components:
  - type: SpawnPoint
    job_id: MessTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: mess_tech
