- type: job
  parent: CMJobBase
  id: CMMessTech
  name: cm-job-name-messtech
  description: cm-job-description-messtech
  playTimeTracker: CMJobMessTech
  startingGear: CMGearMessTech
  icon: "CMJobIconMessTech"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-aso
  canBeAntag: true
  accessGroups:
  - MessTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 1
      domestics: 2
      engineer: 1
      firearms: 2

- type: startingGear
  id: CMGearMessTech
  equipment:
    head: ClothingHeadHatChef
    jumpsuit: CMJumpsuitMessTech
    outerClothing: CMCoatMessTech
    back: CMSatchel
    shoes: CMBootsBrown
    id: CMIDCardMessTech
    ears: CMHeadsetChef

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointMessTech
  name: mess tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMMessTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: mess_tech

- type: playTimeTracker
  id: CMJobMessTech
