- type: job
  id: CMQuartermaster
  parent: JobBaseCM
  name: job-name-cm-quartermaster
  description: job-description-cm-quartermaster
  playTimeTracker: JobCMQuartermaster
  requirements:
    - !type:DepartmentTimeRequirement
      department: Requisitions
      time: 36000 # 10 hours
  weight: 5
  startingGear: CMQuartermasterGear
  icon: "JobIconCMQuartermaster"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-cm14-aso
  canBeAntag: false
  accessGroups:
  - CMQM

- type: startingGear
  id: CMQuartermasterGear
  equipment:
    jumpsuit: CMJumpsuitQM
    back: CMBackpackEngineer
    shoes: CMBootsBrown
    head: CMHeadCapCargo
    gloves: CMHandsBrown
    id: CMQuartermasterIDCard
    ears: CMHeadsetQM
  satchel: CMSatchelEngineer

- type: entity
  id: CMSpawnPointQuartermaster
  parent: CMSpawnPointJobBase
  name: quartermaster spawn point
  components:
  - type: SpawnPoint
    job_id: CMQuartermaster
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: quartermaster
