- type: department
  parent: CMDepartmentBase
  id: CMMilitaryPolice
  description: cm-department-MilitaryPolice-description
  color: "#DE3A3A"
  roles:
  - CMChiefMP
  - CMMilitaryWarden
  - CMMilitaryPolice
