- type: department
  parent: CMDepartmentBase
  id: CMRequisitions
  description: cm-department-Requisitions-description
  color: "#5F4519"
  roles:
  - CMQuartermaster
  - CMCargoTech
  - CMMessTech
