- type: job
  id: CMCombatTech
  parent: CMJobBase
  name: cm-job-name-combat-tech
  description: cm-job-description-combat-tech
  playTimeTracker: CMJobCombatTech
  requirements:
    - !type:DepartmentTimeRequirement
      department: CMMarine
      time: 3600 #1 hrs
  startingGear: CMGearCombatTech
  icon: "CMJobIconCombatTech"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  canBeAntag: false
  accessGroups:
  - CombatTech
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      constructiopn: 2
      engineer: 2
      jtac: 1
      vehicle: 1

- type: startingGear
  id: CMGearCombatTech
  equipment:
    jumpsuit: CMJumpsuitMarineEngineer
    back: CMSatchelMarineTech
    shoes: CMBootsBlackFilled
    eyes: ClothingEyesGlassesMeson
    head: CMArmorHelmetM10Tech
    outerClothing: ArmorMarineM3
    gloves: CMHandsInsulated
    id: CMDogtagCombatTech
    ears: CMHeadsetAlphaEngineer
    belt: CMBeltUtilityCombatFilled

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCombatTech
  name: combat tech spawn point
  components:
  - type: SpawnPoint
    job_id: CMCombatTech
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: combat_tech

- type: playTimeTracker
  id: CMJobCombatTech
