- type: job
  parent: CMJobSquadBase
  id: CMFireteamLeader
  name: cm-job-name-fireteam-leader
  description: cm-job-description-fireteam-leader
  playTimeTracker: CMJobFireteamLeader
  requirements:
    - !type:DepartmentTimeRequirement
      department: CMMarine
      time: 28800 #8 hrs
  startingGear: CMGearFireteamLeader
  icon: "CMJobIconFireteamLeader"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  canBeAntag: false
  accessGroups:
  - FTL
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 2
      engineer: 2
      jtac: 3

- type: startingGear
  id: CMGearFireteamLeader
  equipment:
    jumpsuit: CMJumpsuitMarineRTO
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: CMArmorHelmetM12
    outerClothing: CMArmorM4
    gloves: CMHandsBlack
    id: CMDogtagFireteamLeader
    ears: CMHeadsetAlphaTeamLeader

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointFireteamLeader
  name: fireteam leader spawn point
  components:
  - type: SpawnPoint
    job_id: CMFireteamLeader
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: fireteam_leader

- type: playTimeTracker
  id: CMJobFireteamLeader
