- type: job
  id: Rifleman
  parent: JobBaseCM
  name: job-name-rifleman
  description: job-description-rifleman
  playTimeTracker: JobRifleman
  startingGear: RiflemanGear
  icon: "JobIconRifleman"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-sl
  canBeAntag: false
  accessGroups:
  - Rifleman

- type: startingGear
  id: RiflemanGear
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMBackpackMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: DogtagRifleman
    ears: CMHeadsetAlpha
  satchel: CMSatchelMarine

- type: entity
  id: SpawnPointRifleman
  parent: CMSpawnPointJobBase
  name: rifleman spawn point
  components:
  - type: SpawnPoint
    job_id: Rifleman
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: rifleman
