- type: job
  parent: CMJobBase
  id: CMRifleman
  name: cm-job-name-rifleman
  description: cm-job-description-rifleman
  playTimeTracker: CMJobRifleman
  startingGear: CMGearRifleman
  icon: "CMJobIconRifleman"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  canBeAntag: false
  accessGroups:
  - Rifleman
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills

- type: startingGear
  id: CMGearRifleman
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: CMDogtagRifleman
    ears: CMHeadsetAlpha

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointRifleman
  name: rifleman spawn point
  components:
  - type: SpawnPoint
    job_id: CMRifleman
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: rifleman

- type: playTimeTracker
  id: CMJobRifleman
