- type: job
  id: Smartgunner
  parent: JobBaseCM
  name: job-name-smartgunner
  description: job-description-smartgunner
  playTimeTracker: JobSmartgunner
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 18000 #5 hrs
  startingGear: SmartgunnerGear
  icon: "JobIconSmartgunner"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-sl
  canBeAntag: false
  accessGroups:
  - Smartgunner

- type: startingGear
  id: SmartgunnerGear
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMBackpackMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: DogtagSmartgunner
    ears: CMHeadsetAlpha
  satchel: CMSatchelMarine

- type: entity
  id: SpawnPointSmartGunner
  parent: CMSpawnPointJobBase
  name: smartgunner spawn point
  components:
  - type: SpawnPoint
    job_id: Smartgunner
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: smartgunner
