- type: job
  parent: CMJobSquadBase
  id: CMSmartgunner
  name: cm-job-name-smartgunner
  description: cm-job-description-smartgunner
  playTimeTracker: CMJobSmartgunner
  requirements:
    - !type:DepartmentTimeRequirement
      department: CMMarine
      time: 18000 #5 hrs
  startingGear: CMGearSmartgunner
  icon: "CMJobIconSmartgunner"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  canBeAntag: false
  accessGroups:
  - Smartgunner
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      jtac: 1
      smartgun: 1

- type: startingGear
  id: CMGearSmartgunner
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: CMDogtagSmartgunner
    ears: CMHeadsetAlpha

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSmartGunner
  name: smartgunner spawn point
  components:
  - type: SpawnPoint
    job_id: CMSmartgunner
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: smartgunner

- type: playTimeTracker
  id: CMJobSmartgunner
