- type: job
  id: SquadLeader
  parent: JobBaseCM
  name: job-name-squad-leader
  description: job-description-squad-leader
  playTimeTracker: JobSquadLeader
  requirements:
    - !type:DepartmentTimeRequirement
      department: Marine
      time: 36000 #10 hrs
    - !type:RoleTimeRequirement
      role: JobFireteamLeader
      time: 10800 #3 hrs
  startingGear: SquadLeaderGear
  icon: "JobIconSquadLeader"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-co
  canBeAntag: false
  accessGroups:
  - SquadLeader
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 2
      cqc: 1
      endurance: 2
      engineer: 2
      fireman: 1
      intel: 1
      jtac: 2
      leadership: 1
      medical: 1
      vehicle: 1

- type: startingGear
  id: SquadLeaderGear
  equipment:
    jumpsuit: CMJumpsuitMarineRTO
    back: CMBackpackMarine
    shoes: CMBootsBlackFilled
    head: CMArmorHelmetM11
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: DogtagSquadLeader
    ears: CMHeadsetAlphaLeader
  satchel: CMSatchelMarine

- type: entity
  id: SpawnPointSquadLeader
  parent: CMSpawnPointJobBase
  name: squad leader spawn point
  components:
  - type: SpawnPoint
    job_id: SquadLeader
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: squad_leader
