- type: job
  parent: CMJobBase
  id: CMWeaponsSpecialist
  name: cm-job-name-weapons-specialist
  description: cm-job-description-weapons-specialist
  playTimeTracker: CMJobWeaponsSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: CMMarine
      time: 18000 #5 hrs
  startingGear: CMGearWeaponsSpecialist
  icon: "CMJobIconWeaponsSpecialist"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-sl
  canBeAntag: false
  accessGroups:
  - WeaponSpec
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 1
      construction: 1
      endurance: 2
      engineer: 1
      jtac: 1
      meleeWeapons: 1
      specialistWeapons: 1


- type: startingGear
  id: CMGearWeaponsSpecialist
  equipment:
    jumpsuit: JumpsuitMarine
    back: CMSatchelMarine
    shoes: CMBootsBlackFilled
    head: ArmorHelmetM10
    outerClothing: ArmorMarineM3
    gloves: CMHandsBlack
    id: CMDogtagWeaponsSpecialist
    ears: CMHeadsetAlpha

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointWeaponsSpecialist
  name: weapons specialist spawn point
  components:
  - type: SpawnPoint
    job_id: CMWeaponsSpecialist
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: weapons_specialist

- type: playTimeTracker
  id: CMJobWeaponsSpecialist
