- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconChiefEngineer
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_ce

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconOrdnanceTech
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_ot

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconMaintTech
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_mt
