- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconCombatTech
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_engi

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconFireteamLeader
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_tl

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconHospitalCorpsman
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_med

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconRifleman
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: empty

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconSmartgunner
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_gun

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconSquadLeader
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_leader

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconWeaponsSpecialist
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudsquad_spec
