- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconCorrespondent
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: empty

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconSurvivor
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: empty

- type: statusIcon
  parent: CMJobIconBase
  id: CMJobIconLiaison
  icon:
    sprite: _CM14/Interface/cm_job_icons.rsi
    state: hudW-Y
