- type: job
  parent: CMJobBase
  id: CMCorrespondent
  name: cm-job-name-correspondent
  description: cm-job-description-correspondent
  playTimeTracker: CMJobCorrespondent
  startingGear: CMGearCorrespondent
  icon: "CMJobIconCorrespondent"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-co
  canBeAntag: true
  accessGroups:
  - CMCorrespondent
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
  hasIcon: false

- type: startingGear
  id: CMGearCorrespondent
  equipment:
    jumpsuit: CMJumpsuitCorrespondent
    outerClothing: CMCoatCorrespondent
    back: CMSatchel
    shoes: CMBootsBrown
    id: CMIDCardCorrespondent
    ears: CMHeadsetReporter

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCorrespondent
  name: correspondent spawn point
  components:
  - type: SpawnPoint
    job_id: CMCorrespondent
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: combat_correspondent

- type: playTimeTracker
  id: CMJobCorrespondent
