- type: job
  id: Correspondent
  parent: JobBaseCM
  name: job-name-correspondent
  description: job-description-correspondent
  playTimeTracker: JobCorrespondent
  startingGear: CorrespondentGear
  icon: "JobIconCorrespondent"
  joinNotifyCrew: false
  supervisors: job-supervisors-cm14-co
  canBeAntag: true
  accessGroups:
  - CMCorrespondent

- type: startingGear
  id: CorrespondentGear
  equipment:
    jumpsuit: CMJumpsuitCorrespondent
    outerClothing: CMCoatCorrespondent
    back: CMBackpack
    shoes: CMBootsBrown
    id: CorrespondentIDCard
    ears: CMHeadsetReporter
  satchel: CMSatchel

- type: entity
  id: CMSpawnPointCorrespondent
  parent: CMSpawnPointJobBase
  name: correspondent spawn point
  components:
  - type: SpawnPoint
    job_id: Correspondent
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: combat_correspondent
