- type: job
  parent: CMJobBase
  id: CMLiaison
  name: cm-job-name-liaison
  description: cm-job-description-liaison
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 36000 # 10 hours
  playTimeTracker: CMJobLiaison
  startingGear: CMGearLiaison
  icon: "CMJobIconLiaison"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-wy
  canBeAntag: true
  accessGroups:
  - MarineMain
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 1
      endurance: 2

- type: startingGear
  id: CMGearLiaison
  equipment:
    jumpsuit: CMJumpsuitLiaisonBlack
    back: CMSatchel
    shoes: CMShoesDress
    id: CMIDCardLiaison
    ears: CMHeadsetLeader

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointLiaison
  name: liaison spawn point
  components:
  - type: SpawnPoint
    job_id: CMLiaison
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: corp_liaison
      
- type: playTimeTracker
  id: CMJobLiaison
