- type: job
  parent: CMJobBase
  id: CMSurvivor
  name: cm-job-name-survivor
  description: cm-job-description-survivor
  playTimeTracker: CMJobSurvivor
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobRifleman
    time: 18000 #5 hours
  - !type:RoleTimeRequirement
    role: CMJobHospitalCorpsman
    time: 18000 #5 hours
  - !type:RoleTimeRequirement
    role: CMJobCombatTech
    time: 18000 #5 hours
  startingGear: CMGearSurvivor
  icon: "CMJobIconSurvivor"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-nobody
  canBeAntag: false
  accessGroups:
  - Colonist
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 1
      endurance: 2

- type: startingGear
  id: CMGearSurvivor
  equipment:
    jumpsuit: CMJumpsuitColonist
    back: CMSatchel
    shoes: CMBootsBrown
    id: CMIDCardColonist
    ears: CMHeadsetColony

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointSurvivor
  name: survivor spawn point
  components:
  - type: SpawnPoint
    job_id: CMSurvivor
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: survivor
      
- type: playTimeTracker
  id: CMJobSurvivor
