- type: entity
  save: false
  parent: BaseMobSpecies
  id: CMBaseMobSpeciesOrganic
  abstract: true
  name: Urist C.M. McHands
  suffix: CM14
  components:
  - type: SolutionContainerManager
  - type: InjectableSolution
    solution: chemicals
  - type: Bloodstream
    bloodReagent: Blood
    bloodlossDamage:
      types:
        Bloodloss: 0.5
    bloodlossHealDamage:
      types:
        Bloodloss: -1
  - type: Flashable
  - type: PassiveDamage # Slight passive regen. Assuming one damage type, comes out to about 4 damage a minute.
    allowedStates:
    - Alive
    damageCap: 20
    damage:
      types:
        Heat: -0.07
      groups:
        Brute: -0.07
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
    - Stutter
    - SeeingRainbows
    - Electrocution
    - ForcedSleep
    - TemporaryBlindness
    - Drunk
    - SlurredSpeech
    - RatvarianLanguage
    - PressureImmunity
    - Muted
    - Pacified
    - StaminaModifier
  - type: Blindable
  - type: Tag
    tags:
    - CanPilot
    - FootstepSound
    - DoorBumpOpener
    - ShoesRequiredStepTriggerImmune
  - type: Marine
  - type: Hunger
  - type: Thirst
  - type: Body
    prototype: Human
    requiredLegs: 2
  - type: Damageable
    damageContainer: Biological
    damageModifierSet: null
  - type: Vocal
    sounds:
      Male: MaleHuman
      Female: FemaleHuman
      Unsexed: MaleHuman
  - type: Flammable
    fireSpread: true
    canResistFire: true
    damage:
      types:
        Heat: 3
  - type: Temperature
    heatDamageThreshold: 325
    coldDamageThreshold: 260
    currentTemperature: 310.15
    specificHeat: 42
    coldDamage:
      types:
        Cold: 0.1
    heatDamage:
      types:
        Heat: 1.5
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    implicitHeatRegulation: 500
    sweatHeatRegulation: 2000
    shiveringHeatRegulation: 2000
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 25
  - type: FireVisuals
    sprite: Mobs/Effects/onfire.rsi
    normalState: Generic_mob_burning
    alternateState: Standing
  - type: MeleeWeapon
    soundHit:
      collection: Punch
    angle: 30
    animation: WeaponArcFist
    attackRate: 1
    damage:
      types:
        Blunt: 5
  - type: CMSurgeryTarget
  - type: UserInterface
    interfaces:
    - key: enum.VoiceMaskUIKey.Key
      type: VoiceMaskBoundUserInterface
    - key: enum.HumanoidMarkingModifierKey.Key
      type: HumanoidMarkingModifierBoundUserInterface
    - key: enum.StrippingUiKey.Key
      type: StrippableBoundUserInterface
    - key: enum.HumanoidMarkingModifierKey.Key
      type: HumanoidMarkingModifierBoundUserInterface
    - key: enum.CMSurgeryUIKey.Key
      type: CMSurgeryBui
  - type: Huggable
  - type: Tackleable
  - type: Tackle
    stun: 10
  - type: XenoNestable
