- type: entity
  id: CMClosetBombFilled
  parent: CMClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
##      - id: ClothingHeadHelmetBombSuit
##      - id: ClothingOuterSuitBomb
      - id: CMWirecutter
        prob: 0.9
      - id: CMScrewdriver
        prob: 0.9
      - id: CMMultitool
        prob: 0.5
