# Overall play time tracker is in the original file.
#todo cm14 move all these to their proper roles
# command
- type: playTimeTracker
  id: JobSeniorEnlistedAdvisor

- type: playTimeTracker
  id: JobCommandingOfficer

- type: playTimeTracker
  id: JobExecutiveOfficer

# marine
- type: playTimeTracker
  id: JobRifleman

- type: playTimeTracker
  id: JobSquadLeader

- type: playTimeTracker
  id: JobFireteamLeader

- type: playTimeTracker
  id: JobWeaponsSpecialist

- type: playTimeTracker
  id: JobSmartgunner

- type: playTimeTracker
  id: JobHospitalCorpsman

- type: playTimeTracker
  id: JobCombatTech

- type: playTimeTracker
  id: JobStaffOfficer

# military police
- type: playTimeTracker
  id: JobChiefMP

- type: playTimeTracker
  id: JobMilitaryWarden

- type: playTimeTracker
  id: JobMilitaryPolice

# requisition
- type: playTimeTracker
  id: JobCMQuartermaster

- type: playTimeTracker
  id: JobCMCargoTech

- type: playTimeTracker
  id: JobMessTech

# engineering
- type: playTimeTracker
  id: JobCMChiefEngineer

- type: playTimeTracker
  id: JobOrdnanceTech

- type: playTimeTracker
  id: JobMaintTech

# medical
- type: playTimeTracker
  id: JobMarineCMO

- type: playTimeTracker
  id: JobMarineDoctor

- type: playTimeTracker
  id: JobNurse

- type: playTimeTracker
  id: JobResearcher

# auxiliary support
- type: playTimeTracker
  id: JobAuxiliarySupportOfficer

- type: playTimeTracker
  id: JobPilotOfficer

- type: playTimeTracker
  id: JobDropshipCrewChief

- type: playTimeTracker
  id: JobIntelOfficer

# non uscm
- type: playTimeTracker
  id: JobCorrespondent

- type: playTimeTracker
  id: JobSurvivor

- type: playTimeTracker
  id: CMJobLiaison
