- type: job
  parent: CMJobBase
  id: CMCommandingOfficer
  name: cm-job-name-commanding-officer
  description: cm-job-description-commanding-officer
  playTimeTracker: CMJobCommandingOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMMarine
    time: 54000 # 15 hours
  - !type:DepartmentTimeRequirement
    department: CMEngineering
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: CMMilitaryPolice
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: CMMedical
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: CMCommand
    time: 18000 # 5 hours
  weight: 10
  startingGear: CMGearCommandingOfficer
  icon: "CMJobIconCommandingOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-uscm
  canBeAntag: false
  accessGroups:
  - ShipMasterAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 2
      construction: 2
      fireman: 2
      endurance: 2
      engineer: 2
      execution: 1
      intel: 2
      jtac: 4
      leadership: 3
      medical: 3
      navigations: 1
      overwatch: 1
      police: 2
      powerLoader: 2
      smartgun: 1
      surgery: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearCommandingOfficer
  equipment:
    jumpsuit: CMJumpsuitCO
    back: CMSatchel
    shoes: CMShoesDressCommander
    head: CMHeadBeretCO
    outerClothing: CMCoatOfficer
    id: CMIDCardCommandingOfficer
    ears: CMHeadsetSeniorCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointCommandingOfficer
  name: commanding officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMCommandingOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: commanding_officer
      
- type: playTimeTracker
  id: CMJobCommandingOfficer
