- type: job
  id: CommandingOfficer
  parent: JobBaseCM
  name: job-name-commanding-officer
  description: job-description-commanding-officer
  playTimeTracker: JobCommandingOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: Marine
    time: 54000 # 15 hours
  - !type:DepartmentTimeRequirement
    department: MarineEngineering
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: MilitaryPolice
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 36000 # 10 hours
  - !type:DepartmentTimeRequirement
    department: MarineCommand
    time: 18000 # 5 hours
  weight: 10
  startingGear: CommandingOfficerGear
  icon: "JobIconCommandingOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-cm14-uscm
  canBeAntag: false
  accessGroups:
  - ShipMasterAccess

- type: startingGear
  id: CommandingOfficerGear
  equipment:
    jumpsuit: CMJumpsuitCO
    back: CMBackpackCommand
    shoes: CMShoesDressCommander
    head: CMHeadBeretCO
    outerClothing: CMCoatOfficer
    id: CommandingOfficerIDCard
    ears: CMHeadsetSeniorCommand
  satchel: CMSatchel

- type: entity
  id: SpawnPointCommandingOfficer
  parent: CMSpawnPointJobBase
  name: commanding officer spawn point
  components:
  - type: SpawnPoint
    job_id: CommandingOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: commanding_officer
