- type: job
  parent: CMJobBase
  id: CMExecutiveOfficer
  name: cm-job-name-executive-officer
  description: cm-job-description-executive-officer
  playTimeTracker: CMJobExecutiveOfficer
  requirements:
  - !type:RoleTimeRequirement
    role: CMJobStaffOfficer
    time: 18000 # 5 hours
  - !type:DepartmentTimeRequirement
    department: CMMilitaryPolice
    time: 10800 # 3 hours
  weight: 5
  startingGear: CMGearStaffOfficer
  icon: "CMJobIconExecutiveOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-co
  canBeAntag: false
  accessGroups:
  - MarineMain
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 2
      construction: 2
      endurance: 2
      engineer: 2
      fireman: 2
      intel: 2
      jtac: 4
      leadership: 3
      medical: 3
      navigations: 1
      overwatch: 1
      police: 1
      powerLoader: 2
      surgery: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearExecutiveOfficer
  equipment:
    jumpsuit: CMJumpsuitBO
    back: CMSatchel
    shoes: CMShoesDress
    head: CMHeadCap
    outerClothing: CMCoatOfficer
    id: CMIDCardExecutiveOfficer
    ears: CMHeadsetLeader

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointExecutiveOfficer
  name: executive officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMExecutiveOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: executive_officer
      
- type: playTimeTracker
  id: CMJobExecutiveOfficer
