- type: job
  parent: CMJobBase
  id: CMStaffOfficer
  name: cm-job-name-staff-officer
  description: cm-job-description-staff-officer
  playTimeTracker: CMJobStaffOfficer
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15 hours
  - !type:DepartmentTimeRequirement
    department: CMMilitaryPolice
    time: 3600 # 1 hours
  weight: 5
  startingGear: CMGearStaffOfficer
  icon: "CMJobIconStaffOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: cm-job-supervisors-co
  canBeAntag: false
  accessGroups:
  - MarineMain
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 2
      engineer: 2
      fireman: 1
      intel: 1
      jtac: 3
      leadership: 2
      medical: 2
      overwatch: 1
      police: 1
      powerLoader: 1
      vehicles: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearStaffOfficer
  equipment:
    jumpsuit: CMJumpsuitBO
    back: CMSatchelMarine
    shoes: CMShoesDress
    head: CMHeadCap
    id: CMIDCardStaffOfficer
    ears: CMHeadsetLeader

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointStaffOfficer
  name: staff officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMStaffOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: staff_officer
      
- type: playTimeTracker
  id: CMJobStaffOfficer
