- type: job
  id: StaffOfficer
  parent: JobBaseCM
  name: job-name-staff-officer
  description: job-description-Staff-Officer
  playTimeTracker: JobStaffOfficer
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15 hours
  - !type:DepartmentTimeRequirement
    department: MilitaryPolice
    time: 3600 # 1 hours
  weight: 5
  startingGear: StaffOfficerGear
  icon: "JobIconStaffOfficer"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-cm14-co
  canBeAntag: false
  accessGroups:
  - MarineMain

- type: startingGear
  id: StaffOfficerGear
  equipment:
    jumpsuit: CMJumpsuitBO
    back: CMBackpackCommand
    shoes: CMShoesDress
    head: CMHeadCap
    id: StaffOfficerIDCard
    ears: CMHeadsetLeader
  satchel: CMSatchelMarine

- type: entity
  id: SpawnPointStaffOfficer
  parent: CMSpawnPointJobBase
  name: staff officer spawn point
  components:
  - type: SpawnPoint
    job_id: StaffOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: staff_officer
