- type: job
  id: AuxiliarySupportOfficer
  parent: JobBaseCM
  name: job-name-aso
  description: job-description-aso
  playTimeTracker: JobAuxiliarySupportOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: Marine
    time: 18000 # 5 hours
  weight: 5
  startingGear: ASOGear
  icon: "JobIconASO"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-cm14-co
  canBeAntag: false
  accessGroups:
  - ASO
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      construction: 2
      engineer: 2
      fireman: 1
      intel: 2
      jtac: 3
      leadership: 3
      medical: 2
      navigations: 1
      overwatch: 1
      pilot: 2
      police: 1
      powerLoader: 2
      surgery: 1
      vehicles: 1

- type: startingGear
  id: ASOGear
  equipment:
    jumpsuit: CMJumpsuitBO
    outerClothing: CMCoatASO
    back: CMBackpack
    shoes: CMBootsBrown
    id: ASOIDCard
    ears: CMHeadsetLeader
  satchel: CMSatchel

- type: entity
  id: CMSpawnPointASO
  parent: CMSpawnPointJobBase
  name: auxiliary support officer spawn point
  components:
  - type: SpawnPoint
    job_id: AuxiliarySupportOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: auxiliary_support_officer
