- type: job
  parent: CMJobBase
  id: CMDropshipCrewChief
  name: cm-job-name-dcc
  description: cm-job-description-dcc
  playTimeTracker: CMJobDropshipCrewChief
  startingGear: CMGearDCC
  icon: "CMJobIconDCC"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-po
  canBeAntag: true
  accessGroups:
  - DropshipCrewChief
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      engineer: 2
      jtac: 2
      leadership: 1
      medical: 2
      pilot: 1
      powerLoader: 2
      surgery: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearDCC
  equipment:
    jumpsuit: CMJumpsuitDCC
    outerClothing: CMArmorPlatePilot
    back: CMSatchelMarine
    gloves: CMHandsBrown
    shoes: CMBootsBlackFilled
    head: CMHeadCap
    id: CMIDCardDCC
    ears: CMHeadsetPilot

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointDCC
  name: dropship crew chief spawn point
  components:
  - type: SpawnPoint
    job_id: CMDropshipCrewChief
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: dropship_crew_chief
      
- type: playTimeTracker
  id: CMJobDropshipCrewChief
