- type: job
  parent: CMJobBase
  id: CMIntelOfficer
  name: cm-job-name-intel
  description: cm-job-description-intel
  playTimeTracker: CMJobIntelOfficer
  requirements:
  - !type:DepartmentTimeRequirement
    department: CMMarine
    time: 18000 # 5 hours
  startingGear: CMGearIntelOfficer
  icon: "CMJobIconIntelOfficer"
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-aso
  canBeAntag: false
  accessGroups:
  - IntelOfficer
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      cqc: 1
      engineer: 2
      intel: 2
      jtac: 2
      leadership: 2
      meleeWeapons: 1
      overwatch: 1
      research: 1
    - type: MarineOrders

- type: startingGear
  id: CMGearIntelOfficer
  equipment:
    jumpsuit: CMJumpsuitIO
    outerClothing: CMArmorM4
    back: CMSatchelMarineIntel
    gloves: CMHandsBlack
    shoes: CMBootsBlackFilled
    head: CMArmorHelmetM12
    id: CMIDCardIntelOfficer
    ears: CMHeadsetIntel

- type: entity
  parent: CMSpawnPointJobBase
  id: CMSpawnPointIntelOfficer
  name: intel officer spawn point
  components:
  - type: SpawnPoint
    job_id: CMIntelOfficer
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: intel_officer
      
- type: playTimeTracker
  id: CMJobIntelOfficer
